type Quote {
  type: String! # tweet or text
  content: String! # tweetId for a tweet type quote, otherwise the actual content of a quote
  author: String! # tweetId for a tweet type quote
  source: String! # tweetId for a tweet type quote
  isFeatured: Boolean!
  isRecommended: Boolean!
  category: String!
}

type Query {
  allQuotes: [Quote!]!
  quoteByCategory(category: String): [Quote!]!
  quoteByFeatured(isFeatured: Boolean) : [Quote!]!
  quoteByRecommended(isRecommended: Boolean) : [Quote!]!
}
